### PR TITLE
chore: small correction for demo

### PR DESCRIPTION
**Pull request by hmdebenque**
* implements setter for Parameter class because it is deserialized in API
* ensure ActionForm is serializable

**Please check if the PR fulfills these requirements**
- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] The code coverage on new code is > 75 % for backend and > 95% for frontend
- [x] The new code does not introduce new technical issues (sonar / eslint)
- [x] Functional tests have been performed
- [ ] Docker configuration files for config-std or config-cloud profiles are impacted

### CODE REVIEW

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1094/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1094/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1095/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1095/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1096/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1096/)

**Comment by hmdebenque** [comment]
Merged by hand

**Pull request closed without merging**
