### PR TITLE
chore: disable babel modules to let webpack support ES6 modules

### PR DESCRIPTION
**Pull request by jsomsanith**
**Please check if the PR fulfills these requirements**
- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] The code coverage on new code is > 75 % for backend and > 95% for frontend
- [ ] The new code does not introduce new technical issues (sonar / eslint)
- [ ] Functional tests have been performed

**Please check the browsers you've tested on**
- [ ] Chrome, Firefox, Safari, Edge, IE11
- [ ] No, that's bad, this PR should not be merged !
- [x] No, and no need to

**(Optional) What is the current behavior?**
(Additional information to the Jira)
Babel transform ES6 modules to commonJs modules.

**(Optional) What is the new behavior?**
(Additional information to the Jira)
Babel doesn't do the module transformation, webpack manage the ES6 modules.
This enables tree shaking

**(Optional) Other information**:

| Chunk | Old size | New size |
|---|---|---|
| App | 1.05MB | 983.45 KB |
| Vendor | 1.51MB | 1.51MB |
| All | 3.91MB | 3.82MB |

### CODE REVIEW

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/974/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/974/)

**Comment by jsomsanith** [comment]
Not compatible with ng-annotate :(

**Comment by jsomsanith** [comment]
TODO : Explore https://github.com/schmod/babel-plugin-angularjs-annotate

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/985/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/985/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/999/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/999/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1103/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1103/)

**Pull request closed without merging**
