### PR TITLE
fix(TDP_5057): export empty column

### PR DESCRIPTION
**Pull request by aleboulanger**
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TDP-5057

**Please check if the PR fulfills these requirements**
- [ ] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] The code coverage on new code is > 75 % for backend and > 95% for frontend
- [ ] The new code does not introduce new technical issues (sonar / eslint)
- [ ] Functional tests have been performed
- [ ] Docker configuration files for config-std or config-cloud profiles are impacted

**Please check the browsers you've tested on**
- [ ] Chrome, Firefox, Safari, Edge, IE11
- [ ] No, that's bad, this PR should not be merged !
- [ ] No, and no need to (backend changes only)

### CODE REVIEW

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/15/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/15/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/29/) [:star:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/29/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/70/) [:star:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/70/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/87/) [:star:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/87/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/134/) [:star:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/134/)

**Comment by aleboulanger** [comment]
already done in https://github.com/Talend/data-prep/pull/1095

**Pull request closed without merging**
