### PR TITLE
Feat/tdp 2552 exception dto

### PR DESCRIPTION
**Pull request by hmdebenque**
* add use of DTO to pass on exceptions
* remove useless consumes when:
   - body is an object and deserialized transparently
   - consumes is set to "*/*"
   - body is not used
* remove useless produces when:
   - response is an object thus serialized transparently
   - response is void
* change exception format to camelCase as used for all other entities
  thus allowing use of global ObjectMapper
* remove "isError" from exceptions
* better serialization of error codes using DTO

https://jira.talendforge.org/browse/TDP-2552

**Please check if the PR fulfills these requirements**
- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] The code coverage on new code is > 75 % for backend and > 95% for frontend
- [x] The new code does not introduce new technical issues (sonar / eslint)
- [x] Functional tests have been performed

### CODE REVIEW

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/71/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/71/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/72/) [:star:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/72/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/73/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/73/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/76/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/76/)

**Comment by fhuaulme** [comment]
Approved but unit tests failures on https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/76/console

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/78/) [:star:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/78/)

**Pull request merged**
