### PR TITLE
Smallet/tdp 3798 toggle create new column

### PR DESCRIPTION
**Pull request by smallet**
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TDP-3798

**Please check if the PR fulfills these requirements**
- [x] The commit(s) message(s) follows our [guidelines](https://github.com/talend/tools/blob/master/tools-root-github/CONTRIBUTING.md#commit-message-format)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] The code coverage on new code is > 75 % for backend and > 95% for frontend
- [ ] The new code does not introduce new technical issues (sonar / eslint)
- [x] Functional tests have been performed
- [ ] Docker configuration files for config-std or config-cloud profiles are impacted

**Please check the browsers you've tested on**
- [ ] Chrome, Firefox, Safari, Edge, IE11
- [ ] No, that's bad, this PR should not be merged !
- [x] No, and no need to (backend changes only)

Sub-task 1 of TDP-3798: TDP-4529
 - define framework how manage this new parameter
 - impact on all actions
 - force TU of actions to manage this new param, and add tests on two cases (new col & in-place)

### CODE REVIEW

**Comment by smallet** [comment]
Please review, but do not merge, because it needs other sub-task (especially migration tasks) to be able to merge on master

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/922/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/922/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1041/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1041/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1124/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1124/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1140/) [:star:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1140/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1155/) [:star:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1155/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1156/) [:star:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1156/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1176/) [:star:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1176/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1179/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1179/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1180/) [:star:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1180/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1227/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1227/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1240/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1240/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1242/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1242/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1243/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1243/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1245/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1245/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1246/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1246/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1248/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1248/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1252/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1252/)

**Pull request merged**
