### PR TITLE
feat(TDP-1801/TDQ-14147): support datamasking generate from Dictionaries

### PR DESCRIPTION
**Pull request by msjian**
waiting for https://jira.talendforge.org/browse/TDQ-14147

### CODE REVIEW

**Comment by msjian** [comment]
after https://github.com/Talend/data-quality/pull/235 merged, then do this

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/888/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/888/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1033/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1033/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1060/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/1060/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/16/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/16/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/17/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/17/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/3/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/3/)

**Comment by msjian** [comment]
after https://github.com/Talend/data-quality/pull/286 merged, can merge this

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/77/) [:x:](https://ci-tdp.datapwn.com/job/data-prep_pull-request_master/77/)

**Pull request merged**
