### PR TITLE
TDQ-13269: add Remove trailing and leading characters action and test

### PR DESCRIPTION
**Pull request by msjian**

### CODE REVIEW

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/952/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/952/)

**Comment by sizhaoliu** [comment]
@fhuaulme The library is ready but DP integration is not completed yet. Do you prefer to keep this PR, or cancel this and recreate another one later ?

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/959/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/959/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/961/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/961/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1003/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1003/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1010/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1010/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1011/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1011/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1028/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1028/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1030/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1030/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1031/) [:star:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1031/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [success](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1053/) [:star:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1053/)

**Comment by build-talend-tdp** [comment]
Pull request test result: [failure](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1081/) [:x:](https://ci-tdp.datapwn.com/job/tdp_pull-request_master/1081/)

**Comment by msjian** [comment]
i will create a new PR

**Pull request closed without merging**
